### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlexDrar** [ThatMajesticGuy/Brawl-Stars-Discord-RPC#2]
When i want to install the packages this error shows up
![ScreenShot_20210621115936](https://user-images.githubusercontent.com/86253780/122800723-e6882780-d288-11eb-8ffc-96cfb5d903b7.png)

**Comment by ThatMajesticGuy** [comment]
Sorry for the late response. That's not an error, it is just a couple of unimportant warnings, it still should work.
